on: push
  #  push:
  #    tags:
  #      - 'v*'

name: Build release assets

jobs:
  build:
    name: Create Release
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: sh scripts/package_dmg.sh
      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/lock.dmg
          tag_name: v1.1.1
