on:
  push:
    tags:
      - 'v*'

name: Build release assets

jobs:
  build:
    name: Create Release
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: sh scripts/package_dmg.sh
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://github.com/duksis/Lock/releases/tag/${{ github.ref }}
          asset_path: ./dist/lock.dmg
          asset_name: lock.dmg
          asset_content_type: application/octet-stream
